/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppMain: typeof import('./src/components/AppMain.vue')['default']
    Components: typeof import('./src/components/index.vue')['default']
    ImageInput: typeof import('./src/components/ImageInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextInput: typeof import('./src/components/TextInput.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TicketPreview: typeof import('./src/components/TicketPreview.vue')['default']
  }
}
